### ISSUE TITLE
cannot detect new lines in .ass .srt files

### ISSUE THREAD

**Issue by DhansAL** [ApayRus/frazy-parser#2]
currently using **frazy-parser**  `2.6.1` and faced the same issue with v `^2.4.0` .

### expected output
**used .srt file**
```
68
00:03:40,100 --> 00:03:40,940
すご〜い！

69
00:03:41,770 --> 00:03:45,190
初めての水族館が
和也君とで よかった〜！

70
00:03:56,370 --> 00:03:57,200
（和也）はっ…
```
the parsed output  should contain second line from id 69, instead I got

```
66:
body: Array(1)
0: {text: "すご〜い！"}
end: 220.94
id: 67
identifier: "68"
start: 220.1

67:
body: Array(1)
0: {text: "初めての水族館が"}
//line is missing
length: 1

end: 225.19
id: 68
identifier: "69"
start: 221.77

68:

0: {text: "（和也）はっ…"}
length: 1
__proto__: Array(0)
end: 237.2
id: 69
identifier: "70"
start: 236.37

```
### steps to reproduce

```javascript
 import { parseSubs } from "frazy-parser";
 let data  = 'subfile.srt' || 'subfile.ass';
 let subData = parseSubs(data);
 console.log(subData);
```

**Comment by Aparus** [comment]
> ```javascript
>  let data  = 'subfile.srt' || 'subfile.ass';
> ```
 Hi! You are sending to `parseSubs` name of file. But you should send content of file. 
Something like:

```javascript
import fs from 'fs' 

const data = fs.readFileSync('subtitle.srt')
const subData = parseSubs(data);
```
Read the docs for `fs.readFileSync` for write correct path to the file.

**Comment by DhansAL** [comment]
yeah i tried with fs module 
```javascript

  let data = fs.readFileSync(subfile, "utf-8");
//output from this is .srt data that I mentioned above
   subsArray = parseSubs(data);
// this is the array which I got (newLine missing)

```

P.S. - it works fine when storing srt or ass file data on a variable as a string .

**Comment by Aparus** [comment]
Did you try to console.log data, after reading the file? 
```javascript 
let data = fs.readFileSync(subfile, "utf-8");
console.log(data)
```
To be sure that file had read correctly. 

Can you send me your file? I will check it for hidden symbols. Once I had problem with hidden symbols `\r` on Windows after  the lib was tested on Ubuntu.

**Comment by DhansAL** [comment]
hey, apologies for the late reply.
yes, I tried logging the data on the console here's how it looks like.
`﻿1
00:00:03,260 --> 00:00:05,550
（和也）
俺は木ノ下和也(きのしたかずや) 二十歳

2
00:00:05,720 --> 00:00:08,220
都内で一人暮らしをする大学生だ

3
00:00:08,970 --> 00:00:11,180
ちなみに 彼女はいる

4
00:00:11,890 --> 00:00:13,140
繰り返そう`

its a segment of the data i got after 
```javascript
let data = fs.readFileSync(subfile, "utf-8");
console.log(data)
```
it's the data I received from a **.srt file** and in case of 
**.ass file,**

`﻿[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[Aegisub Project Garbage]

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.80,0:00:02.38,Default,,0,0,0,,（和也(かずや)）ああ…
Dialogue: 0,0:00:02.76,0:00:03.59,Default,,0,0,0,,え？
Dialogue: 0,0:00:03.72,0:00:04.55,Default,,0,0,0,,（千鶴(ちづる)）うっ…
Dialogue: 0,0:00:07.39,0:00:08.22,Default,,0,0,0,,はあ？
Dialogue: 0,0:00:08.97,0:00:10.43,Default,,0,0,0,,（木部(きべ)）何？　和也 知り合い？
Dialogue: 0,0:00:10.56,0:00:11.39,Default,,0,0,0,,え？　あっ いや…
Dialogue: 0,0:00:17.06,0:00:17.94,Default,,0,0,0,,あ…
Dialogue: 0,0:00:18.90,0:00:19.90,Default,,0,0,0,,（木部）誰あれ？`
i got this on console. 

here is the link  for files https://drive.google.com/drive/folders/1NCZwk1epgLQszD-RX-jJiQGwZK4kTdhD?usp=sharing 

yes I took let instead of const but I tried after using const too it wasn't the issue

**Comment by Aparus** [comment]
I'm sorry, for now I can't reproduce your issue. I tried text from your files, and it works... I will do a demo page to run the parser online, maybe then we can understand the reason for the problem.

About schema of `ass`, we discussed earlier, that before parsing you should find/replace
`Dialogue: 0,0:00:00.80,0:00:02.38,Default,,0,0,0,,（和也(かずや)）ああ…`
to
`0:00:00.80,0:00:02.38 （和也(かずや)）ああ…`

I noticed that your `srt` file begins with &#65279, the Unicode Character 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF)

It causes that the first cue (phrase) is not recognized.

After I make a demo page in the coming days and test it on your issue, I will write a comment here. Stay connected.

**Comment by Aparus** [comment]
@DhansAL hi! How are you doing? I have good news. 
* [Playground](https://aparus.github.io/frazy-parser/) for testing parser in real time. 
* default `.ass` schema now is supported. Now your file `rent 2.ass` is parsed without any changes in text. 

I have tested  Playground on both of your files, `rent 1.srt` and `rent 2.ass` and it works for both. 
I hope it will work in your app too. 

![Screenshot from 2021-07-29 00-20-14](https://user-images.githubusercontent.com/1222611/127397695-cb252de8-7232-45b4-a7ad-1fd802c10f64.png)

**Comment by DhansAL** [comment]
Hey Aparus, I am really happy about frazy-parser supporting complex type of .ass files and I just tested your playground. it parses the subs successfully:) but still, the issue for me persists.
I updated my package to `v2.7.1`  and I did  the same steps as earlier,
using file `rent 1.srt`  

```javascript
const testData = fs.readFileSync(
  "path/to/rent 1.srt",
  "UTF-8"
);
console.log(testData);
const checkArr= parseSubs(testData);
console.log(checkArr);
```
what I got  on **console.log(testData)**  is;
```
﻿68
00:03:40,100 --> 00:03:40,940
すご〜い！

69
00:03:41,770 --> 00:03:45,190
初めての水族館が
和也君とで よかった〜！

70
00:03:56,370 --> 00:03:57,200
（和也）はっ…
```
and what i got on **console.log(checkArr)** is;
```javascript
66:
body: Array(1)
0: {text: "すご〜い！"}
length: 1
__proto__: Array(0)
end: 220.94
id: 67
identifier: "68"
start: 220.1
__proto__: Object
67:
body: Array(1)
0: {text: "初めての水族館が"} //missed line 和也君とで よかった〜！
length: 1
__proto__: Array(0)
end: 225.19
id: 68
identifier: "69"
start: 221.77
__proto__: Object
68:
body: Array(1)
0: {text: "（和也）はっ…"}
length: 1
__proto__: Array(0)
end: 237.2
id: 69
identifier: "70"
start: 236.37
__proto__: Object
```
And while running the **same file in Playground** I got the same result,
```javascript
{
		"id": 68,
		"identifier": "68",
		"start": 220.1,
		"end": 220.94,
		"body": [
			{
				"text": "すご〜い！"
			}
		]
	},
	{
		"id": 69,
		"identifier": "69",
		"start": 221.77,
		"end": 225.19,
		"body": [
			{
				"text": "初めての水族館が"
			}
		]
	},
	{
		"id": 70,
		"identifier": "70",
		"start": 236.37,
		"end": 237.2,
		"body": [
			{
				"text": "（和也）はっ…"
			}
		]
	},
```


As you can see, it still misses a line while parsing.
I tried working with other parsers and I don't know if I am right, they used `<br/>` instead of `\N`  and it works(you still have to slice out the <br/> tag out of the string). maybe I'm saying a silly thing but it worked for me.

I forgot to mention my current tech stack for the project,
I'm using React, Electron.js, and Webpack.

**Comment by Aparus** [comment]
@DhansAL , I'm sorry, for my inattention. 
While I was working on `.ass` and playground I forgot about your real issue )) now I saw it. 
Yes it's strange. When you put text to `textarea` line breaks appears as `\n`, but after attaching a file, line breaks disappears.

**Comment by Aparus** [comment]
I tried with other file [en.vtt](https://github.com/Aparus/frazy-parser/files/6900203/en.txt). And it works. Cue 58 has 2 lines in body, and they both are parsed with  `\n` between. You can also try it in Playground or in your code. 

I guess, your file have strange hidden symbols, that appears only on reading a file. But when you copy file content to clipboard, they disappear. Can you analyze your file for hidden symbols? I'll do it too.

**Comment by DhansAL** [comment]
yeah, I guess you're right. I'll try to work with different .srt and .ass files on playground and check for line breaks.
